### PR TITLE
Closes softlayer/sl-ember-translate#188

### PR DESCRIPTION
**Pull request by notmessenger**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-translate/213)

### CODE REVIEW

**Comment by juwara0** [comment]
I am reviewing this.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/213)

**Comment by juwara0** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[tests/unit/services/sl-translate-test.js, line 18 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/213#-K162yEn4XFAyNW8Clf5)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/a7dfe725dcd7eedcedb2ede070fcc7b1b116737e/tests/unit/services/sl-translate-test.js#L18)):</sup>
Where is the container property? I have opened an issue to remove this assertion: https://github.com/softlayer/sl-ember-translate/issues/215


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/213)

**Comment by juwara0** [comment]
I have finished reviewing this and it is ready for merging.


---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/213)

**Comment by notmessenger** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/213)

**Pull request merged**
