### PR TITLE
Deprecation warning: You modified translatedString twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-translate/200)

### CODE REVIEW

**Comment by erangeles** [comment]
2 failing tests, please do not review yet.

**Comment by notmessenger** [comment]
Reviewed 4 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by erangeles** [comment]
@notmessenger fixed failing tests, ready to be reviewed.

**Comment by notmessenger** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[addon/components/sl-translate.js, line 59 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K06laAOwvte4S9jbR_T)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/6c206a422cece29ecbd638f8bf22039ead98f121/addon/components/sl-translate.js#L59)):</sup>
* Capitalize the first letter of the line
* Lower case the `T` and `S` in `Translated String`


---

<sup>**[addon/components/sl-translate.js, line 68 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K06mBF8XybmrqrwKeae)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/6c206a422cece29ecbd638f8bf22039ead98f121/addon/components/sl-translate.js#L68)):</sup>
* Is missing `@function` tag
* Is missing `@returns` tag
* Should not contain `@type` tag


---

<sup>**[addon/components/sl-translate.js, line 70 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K06lw3buoQMSf3eWgxJ)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/6c206a422cece29ecbd638f8bf22039ead98f121/addon/components/sl-translate.js#L70)):</sup>
Is in the wrong section of the document


---

<sup>**[tests/dummy/app/controllers/demo.js, line 8 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K079EELStPgDrmqXqrh)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/6c206a422cece29ecbd638f8bf22039ead98f121/tests/dummy/app/controllers/demo.js#L8)):</sup>
Add an empty line after this one


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by notmessenger** [comment]
"Update Values" button in demo app is not updating values in the template


---

Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by erangeles** [comment]
for tracking purposes.
https://github.com/wycats/handlebars.js/issues/1050

**Comment by erangeles** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[addon/components/sl-translate.js, line 59 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K06laAOwvte4S9jbR_T)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/6c206a422cece29ecbd638f8bf22039ead98f121/addon/components/sl-translate.js#L59)):</sup>
Done.


---

<sup>**[addon/components/sl-translate.js, line 68 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K06mBF8XybmrqrwKeae)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/6c206a422cece29ecbd638f8bf22039ead98f121/addon/components/sl-translate.js#L68)):</sup>
Done.


---

<sup>**[addon/components/sl-translate.js, line 70 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K06lw3buoQMSf3eWgxJ)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/6c206a422cece29ecbd638f8bf22039ead98f121/addon/components/sl-translate.js#L70)):</sup>
Done.


---

<sup>**[tests/dummy/app/controllers/demo.js, line 8 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K079EELStPgDrmqXqrh)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/6c206a422cece29ecbd638f8bf22039ead98f121/tests/dummy/app/controllers/demo.js#L8)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by notmessenger** [comment]
Once you have made all of the modification to addon/components/sl-translate.js take another look at it and see if we still need as many moving pieces as well have to accomplish our goals.  I feel like we might be able to simplify it further but it's hard to get a sense of given the number of comments I made that will result in code changes.  Will need to see it afterwards to get a better picture.


---

Reviewed 1 of 3 files at r2, 1 of 4 files at r6, 1 of 1 files at r9.
Review status: 3 of 5 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

<sup>**[addon/components/sl-translate.js, line 38 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0WkHRdpIra0othVwgf)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/106c288199a12b8a324f79e4c18544900db60262/addon/components/sl-translate.js#L38)):</sup>
Is this property needed anymore after the refactor?


---

<sup>**[addon/components/sl-translate.js, line 43 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0WkRJutgyzUkYx7HOQ)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/106c288199a12b8a324f79e4c18544900db60262/addon/components/sl-translate.js#L43)):</sup>
Is this description completely accurate anymore after the refactor?


---

<sup>**[addon/components/sl-translate.js, line 99 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0Wnx0yltKRm0BYNWy6)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/106c288199a12b8a324f79e4c18544900db60262/addon/components/sl-translate.js#L99)):</sup>
Do not write this comment in the context of representing the differences between what was being done and what is now, but instead to explain what currently being done.  As such it can be much shorter and succinct.


---

<sup>**[addon/components/sl-translate.js, line 106 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0WvntMUs-MBTc4fe1w)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/106c288199a12b8a324f79e4c18544900db60262/addon/components/sl-translate.js#L106)):</sup>
Does not follow https://github.com/softlayer/ember-style-guide#do-not-redefine-the-willinsertelement-didinsertelement-willclearrender-willdestroyelement-or-diddestroyelement-methods-or-do-so-with-full-knowledge-of-what-you-are-doing


---

<sup>**[addon/components/sl-translate.js, line 137 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0WnIGFuzJSqLFjKyfp)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/106c288199a12b8a324f79e4c18544900db60262/addon/components/sl-translate.js#L137)):</sup>
Can this logic be replaced/combined with that from `extractParameterKeys()`and `extractParameterKeys()` be removed?  `extractParameterKeys()` used to be needed because there were multiple methods (since removed) that were using the arrays it was populated.


---

<sup>**[addon/components/sl-translate.js, line 158 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0Wn2oq9_RXqSf7POlB)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/106c288199a12b8a324f79e4c18544900db60262/addon/components/sl-translate.js#L158)):</sup>
Is this line needed?  Doesn't the call to the same method in `willRender()` take care of things or am I not understanding the timing of things correctly?


---

<sup>**[addon/components/sl-translate.js, line 79 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0WwDFTECteoixgGn0n)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/4648dd31f11b82abc84027123142fdfa0de0a4dc/addon/components/sl-translate.js#L79)):</sup>
What is the reason for these checks?  Know you mentioned it briefly on the call but I haven't fully dug into it for understanding.


---

<sup>**[addon/components/sl-translate.js, line 84 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0WwcX0ujyHgf11LrME)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/4648dd31f11b82abc84027123142fdfa0de0a4dc/addon/components/sl-translate.js#L84)):</sup>
Shouldn't we keep this restricted to just numbers to enforce current behavior?  It can then be relaxed once https://github.com/softlayer/sl-ember-translate/issues/6 is addressed.


---

<sup>**[tests/unit/components/sl-translate-test.js, line 42 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0X-RZS8M1Q03Njekvp)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/4648dd31f11b82abc84027123142fdfa0de0a4dc/tests/unit/components/sl-translate-test.js#L42)):</sup>
Knowing where we are heading with the tests - https://github.com/softlayer/sl-ember-translate/issues/208 - you don't have to bother adding this assertion if you don't want to.


---

<sup>**[tests/unit/components/sl-translate-test.js, line 48 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0X-m-7t9rtXt-BWKNf)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/4648dd31f11b82abc84027123142fdfa0de0a4dc/tests/unit/components/sl-translate-test.js#L48)):</sup>
Comment can be removed.  If the test needs more explanation or clarity then refine the description of the test.


---

<sup>**[tests/unit/components/sl-translate-test.js, line 63 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0X-zVxrIFe6FcAN-8y)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/4648dd31f11b82abc84027123142fdfa0de0a4dc/tests/unit/components/sl-translate-test.js#L63)):</sup>
Are we manipulating properties like we were before?  If not, change the comment.  If not, is this test even any long necessary?


---

<sup>**[tests/unit/components/sl-translate-test.js, line 125 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0X0gumCNcUWizDywQ9)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/4648dd31f11b82abc84027123142fdfa0de0a4dc/tests/unit/components/sl-translate-test.js#L125)):</sup>
The spacing employed in the array syntax passes linting?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by notmessenger** [comment]
Reviewed 2 of 4 files at r6.
Review status: 4 of 5 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by erangeles** [comment]
Review status: 3 of 5 files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

<sup>**[addon/components/sl-translate.js, line 38 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0WkHRdpIra0othVwgf)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/106c288199a12b8a324f79e4c18544900db60262/addon/components/sl-translate.js#L38)):</sup>
no longer needed thus removed.


---

<sup>**[addon/components/sl-translate.js, line 43 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0WkRJutgyzUkYx7HOQ)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/106c288199a12b8a324f79e4c18544900db60262/addon/components/sl-translate.js#L43)):</sup>
this prop is no longer needed thus removed


---

<sup>**[addon/components/sl-translate.js, line 99 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0Wnx0yltKRm0BYNWy6)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/106c288199a12b8a324f79e4c18544900db60262/addon/components/sl-translate.js#L99)):</sup>
fixed doc block.


---

<sup>**[addon/components/sl-translate.js, line 106 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0WvntMUs-MBTc4fe1w)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/106c288199a12b8a324f79e4c18544900db60262/addon/components/sl-translate.js#L106)):</sup>
fixed.


---

<sup>**[addon/components/sl-translate.js, line 137 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0WnIGFuzJSqLFjKyfp)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/106c288199a12b8a324f79e4c18544900db60262/addon/components/sl-translate.js#L137)):</sup>
refactored code.


---

<sup>**[addon/components/sl-translate.js, line 158 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0Wn2oq9_RXqSf7POlB)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/106c288199a12b8a324f79e4c18544900db60262/addon/components/sl-translate.js#L158)):</sup>
removed.


---

<sup>**[addon/components/sl-translate.js, line 79 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0WwDFTECteoixgGn0n)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/4648dd31f11b82abc84027123142fdfa0de0a4dc/addon/components/sl-translate.js#L79)):</sup>
`this.attr` is on hold, thus removed conditional.


---

<sup>**[addon/components/sl-translate.js, line 84 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0WwcX0ujyHgf11LrME)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/4648dd31f11b82abc84027123142fdfa0de0a4dc/addon/components/sl-translate.js#L84)):</sup>
fixed.


---

<sup>**[tests/unit/components/sl-translate-test.js, line 42 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0X-RZS8M1Q03Njekvp)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/4648dd31f11b82abc84027123142fdfa0de0a4dc/tests/unit/components/sl-translate-test.js#L42)):</sup>
forthcoming test push I will address #208 .


---

<sup>**[tests/unit/components/sl-translate-test.js, line 48 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0X-m-7t9rtXt-BWKNf)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/4648dd31f11b82abc84027123142fdfa0de0a4dc/tests/unit/components/sl-translate-test.js#L48)):</sup>
removing in forthcoming test push.


---

<sup>**[tests/unit/components/sl-translate-test.js, line 63 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0X-zVxrIFe6FcAN-8y)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/4648dd31f11b82abc84027123142fdfa0de0a4dc/tests/unit/components/sl-translate-test.js#L63)):</sup>
removing in forthcoming test push.


---

<sup>**[tests/unit/components/sl-translate-test.js, line 125 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0X0gumCNcUWizDywQ9)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/4648dd31f11b82abc84027123142fdfa0de0a4dc/tests/unit/components/sl-translate-test.js#L125)):</sup>
yes it did.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by erangeles** [comment]
forthcoming test push.

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r14.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[addon/components/sl-translate.js, line 45 \[r14\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0l4vW-VtqZRHVpha51)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/9a7d233b66ca02f24a2fc175e6ac7e7d75b482f1/addon/components/sl-translate.js#L45)):</sup>
This needs to be moved to the appropriate document section, per https://github.com/softlayer/ember-style-guide#file-structure-2


---

<sup>**[tests/unit/components/sl-translate-test.js, line 45 \[r14\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0l7b3dPwBBfgZz_tOk)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/9a7d233b66ca02f24a2fc175e6ac7e7d75b482f1/tests/unit/components/sl-translate-test.js#L45)):</sup>
`extractParameterKeys()` does not exist anymore

Think this entire test needs to be revisited, but will do so in https://github.com/softlayer/sl-ember-translate/issues/208


---

<sup>**[tests/unit/components/sl-translate-test.js, line 63 \[r14\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0lADu_NXv6yFn_NTLo)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/9a7d233b66ca02f24a2fc175e6ac7e7d75b482f1/tests/unit/components/sl-translate-test.js#L63)):</sup>
This test case is skipping too many steps along the way.  Based on the description, and start with the first part of it, I would expect to see that a call to `setTranslatedString()` sets the `internalTranslatedString` value and calls `translateString()`.  And that's it.  That tests `setTranslatedString()` as a single unit.

Then there would be a test case to test the `translateString()` logic in isolation.  `translatedString()` would also have its own tests.  How all of these pieces work together to form a single unit is the job of integration tests.  Unit tests should test the output of code with known inputs and no external inputs/calls.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by erangeles** [comment]
Review status: 3 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[addon/components/sl-translate.js, line 45 \[r14\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0l4vW-VtqZRHVpha51)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/9a7d233b66ca02f24a2fc175e6ac7e7d75b482f1/addon/components/sl-translate.js#L45)):</sup>
Done.


---

<sup>**[tests/unit/components/sl-translate-test.js, line 45 \[r14\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0l7b3dPwBBfgZz_tOk)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/9a7d233b66ca02f24a2fc175e6ac7e7d75b482f1/tests/unit/components/sl-translate-test.js#L45)):</sup>
Done.


---

<sup>**[tests/unit/components/sl-translate-test.js, line 63 \[r14\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K0lADu_NXv6yFn_NTLo)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/9a7d233b66ca02f24a2fc175e6ac7e7d75b482f1/tests/unit/components/sl-translate-test.js#L63)):</sup>
added test for setTranslatedString, adding tests for translatedString()


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by notmessenger** [comment]
There needs to a test that asserts that `this.setTranslatedString()` is called when the `willRender()` event occurs.


---

Reviewed 3 of 4 files at r15, 2 of 2 files at r18.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[package.json, line 39 \[r15\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K1-3IGz3XSWgna6jCyu)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/6a6703fb6a1a3acabcb1ace47d8f0df4d4a78283/package.json#L39)):</sup>
Did this come about due to the installation of `ember-sinon`?


---

<sup>**[tests/unit/components/sl-translate-test.js, line 45 \[r15\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K1-3tAi0rn11JsUk762)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/6a6703fb6a1a3acabcb1ace47d8f0df4d4a78283/tests/unit/components/sl-translate-test.js#L45)):</sup>
Put the test description on its own line as well, so that the function definition doesn't get "lost"


---

<sup>**[tests/unit/components/sl-translate-test.js, line 137 \[r18\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K1-6Dyjsj1LhT4pqCfD)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/21ca2754eaf843141a741e23ec746200d4c991ce/tests/unit/components/sl-translate-test.js#L137)):</sup>
Wondered why `$19` isn't also expected.  Then realized that the regex was (originally too) setup to only accept single-digit values.  It should be changed to accept any length of numerical values.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by notmessenger** [comment]
<sup>**[package.json, line 57 \[r18\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K1-9XUgkSsR-NUDgUw6)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/21ca2754eaf843141a741e23ec746200d4c991ce/package.json#L57)):</sup>
I recommend you install version `0.2.1`, to align with the installed version in all the other add-on repos.  The release notes for `0.3.0` say

> Explicit QUnit support is removed in version 0.3.0. You should use ember-sinon-qunit instead.

which we need to research the impact of.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by erangeles** [comment]
addition of "this.setTranslatedString() is called when the willRender() event occurs." test.


---

Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[package.json, line 39 \[r15\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K1-3IGz3XSWgna6jCyu)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/6a6703fb6a1a3acabcb1ace47d8f0df4d4a78283/package.json#L39)):</sup>
It was, removed since it was deemed needed. 


---

<sup>**[package.json, line 57 \[r18\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K1-9XUgkSsR-NUDgUw6)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/21ca2754eaf843141a741e23ec746200d4c991ce/package.json#L57)):</sup>
reverted version.


---

<sup>**[tests/unit/components/sl-translate-test.js, line 45 \[r15\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K1-3tAi0rn11JsUk762)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/6a6703fb6a1a3acabcb1ace47d8f0df4d4a78283/tests/unit/components/sl-translate-test.js#L45)):</sup>
done.


---

<sup>**[tests/unit/components/sl-translate-test.js, line 137 \[r18\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K1-6Dyjsj1LhT4pqCfD)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/21ca2754eaf843141a741e23ec746200d4c991ce/tests/unit/components/sl-translate-test.js#L137)):</sup>
Done. updated regex and test.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by notmessenger** [comment]
Reviewed 3 of 3 files at r19, 1 of 1 files at r20.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/unit/components/sl-translate-test.js, line 159 \[r19\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K14FoYgwNp66oYaCjjt)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/827d40a18bec93d09e8535f780b527e32ed159e2/tests/unit/components/sl-translate-test.js#L159)):</sup>
Spelling of "evenet"


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by erangeles** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[tests/unit/components/sl-translate-test.js, line 159 \[r19\]](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200#-K14FoYgwNp66oYaCjjt)** ([raw file](https://github.com/softlayer/sl-ember-translate/blob/827d40a18bec93d09e8535f780b527e32ed159e2/tests/unit/components/sl-translate-test.js#L159)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r21.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-translate/200)

**Comment by erangeles** [comment]
@notmessenger the "build" badge on our github repo is 'failing'. I click on it and it says the build is passing in the 'build history' tab. not sure why the build badge isnt reflecting that.

**Comment by notmessenger** [comment]
@erangeles Because it looks at the default branch of the repo (which is master) and only updates itself when there is a push to the branch, which there hasn't been in some time.  At some point between when there last was and the status was checked either there was a build failure due to either code or to the CI environment having an issue (most likely the case).  When the EmberCLI-1.13.6 branch gets merged into master this should become resolved.

**Pull request merged**
